defaults: &DEFAULTS
    adapter: mysql2
    encoding: utf8
    reconnect: true
    pool: 5
    host: localhost
    username: railsSQL
    password: rails3D

development:
    <<: *DEFAULTS
    database: UberabaD

production:
    <<: *DEFAULTS
    database: UberabaP

test:
    <<: *DEFAULTS
    database: UberabaT
